#!/usr/bin/env bash

set -e

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$BASE/setEnvVars"

docker build -t $PY_BUILD\
    --build-arg app_version=$APP_VERSION \
     --build-arg PYTHON_VERSION=$PYTHON_VERSION \
     $BASE/builds/python


docker build -t $PSQL_BUILD \
    --build-arg app_version=$APP_VERSION \
     --build-arg POSTGRES_VERSION=$POSTGRES_VERSION \
     $BASE/builds/postgres


