#!/usr/bin/env bash
set -e

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$BASE/setEnvVars"

PYAPPS=$BASE/python
PYDATA=$BASE/coviddata

[ -d $PYDATA ] || mkdir -p "$PYDATA"

if [ "$(ls -A $PYDATA)" ]; then
    rm -rf $PYDATA && mkdir -p "$PYDATA"
elif [ ! -d $PYDATA ]; then
    mkdir -p "$PYDATA"
fi

docker run -d --name $PY_CONTAINER_NAME \
	   -v "$PYAPPS":"/apps" \
	   -v "$PYDATA":"/data" \
	   $PY_BUILD python3 /apps/app.py || false

exit 0;