CREATE USER IF NOT EXISTS coviduser WITH PASSWORD 'covidpass';

CREATE DATABASE IF NOT EXISTS coviddb;

USE coviddb;

GRANT ALL ON DATABASE covid TO coviduser;

CREATE TABLE IF NOT EXISTS TEST (
  id UUID NOT NULL,
  city STRING NOT NULL,
  name STRING,
  dl STRING UNIQUE,
CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC)
);

CREATE INDEX IF NOT EXISTS name_idx ON TEST (dl DESC);